### ISSUE TITLE
intexration links zijn down

### ISSUE THREAD

**Issue by Haroenv** [NorfairKing/Gegevensbanken-Tutorials#1]

**Comment by NorfairKing** [comment]
InteXration is dan ook deprecated. Zie hier: http://cs-syd.eu/projects/notes.html voor pdf's.

**Comment by Haroenv** [comment]
Ah, oké, de link in de README zou dan best aangepast worden

**Comment by NorfairKing** [comment]
True! Ga je gang, als je wil. Github toont me dat er niet genoeg visitors zijn om statistieken te tonenn dus ik denk niet dat het de moeite waard is om het zelf te doen.
